### ISSUE TITLE
Products: upon changing attribute need to reset value field and attribute designation on right

### ISSUE THREAD

**Issue by juliemuraski** [BestBuyAPIs/bby-query-mixer#47]
In this example started with BestSellingRank=1 and then switched to Color. The 1 should reset and the attribute identifier on right should have no attribute value

![image](https://cloud.githubusercontent.com/assets/6863908/5925775/a2233598-a62b-11e4-8ff1-6e1cdb5f639e.png)

**Comment by cmlizama** [comment]
I can do this with an ng-change directive

**Comment by juliemuraski** [comment]
Behavior also present on Open Box

![image](https://cloud.githubusercontent.com/assets/6863908/5963920/e15d82d2-a7b5-11e4-88b2-09e2ee9b96cc.png)

**Comment by cmlizama** [comment]
fixed with 1a091e0c10e56d67e52460c8f31d1bd8d8b55e9c
![screen shot 2015-01-29 at 1 34 23 pm](https://cloud.githubusercontent.com/assets/5415869/5964669/9082f472-a7bb-11e4-8459-d9154cee709b.png)
![screen shot 2015-01-29 at 1 34 55 pm](https://cloud.githubusercontent.com/assets/5415869/5964678/a641e4f8-a7bb-11e4-8596-b5af69e8cf68.png)
